"""add user avatar table

Revision ID: 0dbd5915a0b1
Revises: e1abc1f14621
Create Date: 2025-12-28 17:27:05.174158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbd5915a0b1'
down_revision: Union[str, None] = 'e1abc1f14621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_avatars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_stats_user_id_key', 'user_stats', type_='unique')
    op.create_foreign_key(None, 'user_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_stats', 'id')
    op.add_column('users', sa.Column('active_avatar_url', sa.String(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'eula_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('ux_provider_provider_user', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ux_provider_provider_user', 'users', ['provider', 'provider_user_id'])
    op.alter_column('users', 'eula_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'active_avatar_url')
    op.add_column('user_stats', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.create_unique_constraint('user_stats_user_id_key', 'user_stats', ['user_id'])
    op.drop_table('user_avatars')
    op.drop_table('guest_sessions')
    # ### end Alembic commands ###
