"""Add llm_choice_id to summary_cache

Revision ID: 566010ef5fe6
Revises: d0a5c466bdfb
Create Date: 2026-03-09 17:15:43.790073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566010ef5fe6'
down_revision: Union[str, None] = 'd0a5c466bdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_cache', sa.Column('llm_choice_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'summary_cache', 'llm_choices', ['llm_choice_id'], ['id'], ondelete='CASCADE')
    op.drop_column('summary_cache', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_cache', sa.Column('provider', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'summary_cache', type_='foreignkey')
    op.drop_column('summary_cache', 'llm_choice_id')
    # ### end Alembic commands ###
