"""add summary_cache table

Revision ID: d0a5c466bdfb
Revises: e601ff305efc
Create Date: 2026-03-09 17:00:56.009258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a5c466bdfb'
down_revision: Union[str, None] = 'e601ff305efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pdf_hash', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_cache_pdf_hash'), 'summary_cache', ['pdf_hash'], unique=False)
    op.create_index(op.f('ix_summary_cache_user_id'), 'summary_cache', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_cache_user_id'), table_name='summary_cache')
    op.drop_index(op.f('ix_summary_cache_pdf_hash'), table_name='summary_cache')
    op.drop_table('summary_cache')
    # ### end Alembic commands ###
